/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BasketCreate model module.
 * @module model/BasketCreate
 * @version 0.1.0
 */
export default class BasketCreate {
  /**
   * Constructs a new <code>BasketCreate</code>.
   * @alias module:model/BasketCreate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BasketCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BasketCreate} obj Optional instance to populate.
   * @return {module:model/BasketCreate} The populated <code>BasketCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BasketCreate();
      if (data.hasOwnProperty('product_id'))
        obj.productId = ApiClient.convertToType(data['product_id'], 'Number');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} productId
 */
BasketCreate.prototype.productId = undefined;

/**
 * @member {Number} _number
 */
BasketCreate.prototype._number = undefined;

