/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BasketAdd model module.
 * @module model/BasketAdd
 * @version 0.1.0
 */
export default class BasketAdd {
  /**
   * Constructs a new <code>BasketAdd</code>.
   * @alias module:model/BasketAdd
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BasketAdd</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BasketAdd} obj Optional instance to populate.
   * @return {module:model/BasketAdd} The populated <code>BasketAdd</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BasketAdd();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
BasketAdd.prototype.id = undefined;

