/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import BasketAdd from './BasketAdd';

/**
 * The OrderCreate model module.
 * @module model/OrderCreate
 * @version 0.1.0
 */
export default class OrderCreate {
  /**
   * Constructs a new <code>OrderCreate</code>.
   * @alias module:model/OrderCreate
   * @class
   * @param basket {Array.<module:model/BasketAdd>} 
   * @param paymentType {String} 
   */
  constructor(basket, paymentType) {
    this.basket = basket;
    this.paymentType = paymentType;
  }

  /**
   * Constructs a <code>OrderCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderCreate} obj Optional instance to populate.
   * @return {module:model/OrderCreate} The populated <code>OrderCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderCreate();
      if (data.hasOwnProperty('basket'))
        obj.basket = ApiClient.convertToType(data['basket'], [BasketAdd]);
      if (data.hasOwnProperty('payment_type'))
        obj.paymentType = ApiClient.convertToType(data['payment_type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/BasketAdd>} basket
 */
OrderCreate.prototype.basket = undefined;

/**
 * @member {String} paymentType
 */
OrderCreate.prototype.paymentType = undefined;

