/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductBase model module.
 * @module model/ProductBase
 * @version 0.1.0
 */
export default class ProductBase {
  /**
   * Constructs a new <code>ProductBase</code>.
   * @alias module:model/ProductBase
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductBase} obj Optional instance to populate.
   * @return {module:model/ProductBase} The populated <code>ProductBase</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductBase();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('id_number'))
        obj.idNumber = ApiClient.convertToType(data['id_number'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'Number');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
      if (data.hasOwnProperty('is_ordered'))
        obj.isOrdered = ApiClient.convertToType(data['is_ordered'], 'Number');
      if (data.hasOwnProperty('price100'))
        obj.price100 = ApiClient.convertToType(data['price100'], 'Number');
      if (data.hasOwnProperty('price25'))
        obj.price25 = ApiClient.convertToType(data['price25'], 'Number');
      if (data.hasOwnProperty('percentage'))
        obj.percentage = ApiClient.convertToType(data['percentage'], 'Number');
      if (data.hasOwnProperty('deadline'))
        obj.deadline = ApiClient.convertToType(data['deadline'], 'Date');
      if (data.hasOwnProperty('company_name'))
        obj.companyName = ApiClient.convertToType(data['company_name'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
      if (data.hasOwnProperty('branch_id'))
        obj.branchId = ApiClient.convertToType(data['branch_id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
ProductBase.prototype.code = undefined;

/**
 * @member {Number} idNumber
 */
ProductBase.prototype.idNumber = undefined;

/**
 * @member {Number} name
 */
ProductBase.prototype.name = undefined;

/**
 * @member {Number} _number
 */
ProductBase.prototype._number = undefined;

/**
 * @member {Number} isOrdered
 */
ProductBase.prototype.isOrdered = undefined;

/**
 * @member {Number} price100
 */
ProductBase.prototype.price100 = undefined;

/**
 * @member {Number} price25
 */
ProductBase.prototype.price25 = undefined;

/**
 * @member {Number} percentage
 */
ProductBase.prototype.percentage = undefined;

/**
 * @member {Date} deadline
 */
ProductBase.prototype.deadline = undefined;

/**
 * @member {Number} companyName
 */
ProductBase.prototype.companyName = undefined;

/**
 * @member {Number} status
 */
ProductBase.prototype.status = undefined;

/**
 * @member {Number} branchId
 */
ProductBase.prototype.branchId = undefined;

