/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TradeUpdate model module.
 * @module model/TradeUpdate
 * @version 0.1.0
 */
export default class TradeUpdate {
  /**
   * Constructs a new <code>TradeUpdate</code>.
   * @alias module:model/TradeUpdate
   * @class
   * @param id {Number} 
   * @param status {Boolean} 
   */
  constructor(id, status) {
    this.id = id;
    this.status = status;
  }

  /**
   * Constructs a <code>TradeUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TradeUpdate} obj Optional instance to populate.
   * @return {module:model/TradeUpdate} The populated <code>TradeUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TradeUpdate();
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], 'Number');
      if (data.hasOwnProperty('product_id'))
        obj.productId = ApiClient.convertToType(data['product_id'], 'Number');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} orderId
 */
TradeUpdate.prototype.orderId = undefined;

/**
 * @member {Number} productId
 */
TradeUpdate.prototype.productId = undefined;

/**
 * @member {Number} userId
 */
TradeUpdate.prototype.userId = undefined;

/**
 * @member {Number} _number
 */
TradeUpdate.prototype._number = undefined;

/**
 * @member {Number} id
 */
TradeUpdate.prototype.id = undefined;

/**
 * @member {Boolean} status
 */
TradeUpdate.prototype.status = undefined;

