/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserUpdate model module.
 * @module model/UserUpdate
 * @version 0.1.0
 */
export default class UserUpdate {
  /**
   * Constructs a new <code>UserUpdate</code>.
   * @alias module:model/UserUpdate
   * @class
   * @param name {String} 
   * @param username {String} 
   * @param password {String} 
   * @param id {Number} 
   * @param balance {Number} 
   */
  constructor(name, username, password, id, balance) {
    this.name = name;
    this.username = username;
    this.password = password;
    this.id = id;
    this.balance = balance;
  }

  /**
   * Constructs a <code>UserUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserUpdate} obj Optional instance to populate.
   * @return {module:model/UserUpdate} The populated <code>UserUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserUpdate();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('balance'))
        obj.balance = ApiClient.convertToType(data['balance'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
UserUpdate.prototype.name = undefined;

/**
 * @member {String} username
 */
UserUpdate.prototype.username = undefined;

/**
 * @member {String} password
 */
UserUpdate.prototype.password = undefined;

/**
 * @member {Number} id
 */
UserUpdate.prototype.id = undefined;

/**
 * @member {Number} balance
 */
UserUpdate.prototype.balance = undefined;

