/*
 * Meros web app
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserCreate model module.
 * @module model/UserCreate
 * @version 0.1.0
 */
export default class UserCreate {
  /**
   * Constructs a new <code>UserCreate</code>.
   * @alias module:model/UserCreate
   * @class
   * @param name {String} 
   * @param username {String} 
   * @param password {String} 
   */
  constructor(name, username, password) {
    this.name = name;
    this.username = username;
    this.password = password;
  }

  /**
   * Constructs a <code>UserCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCreate} obj Optional instance to populate.
   * @return {module:model/UserCreate} The populated <code>UserCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserCreate();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
UserCreate.prototype.name = undefined;

/**
 * @member {String} username
 */
UserCreate.prototype.username = undefined;

/**
 * @member {String} password
 */
UserCreate.prototype.password = undefined;

